title: "HOPL License"
description: "Human Only Public License — because GNU won't save you"
baseurl: ""
url: ""

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
  - tailwind.config.js
  - postcss.config.js
  - scripts
  - src
  - generated
  - "*.config.js"
  - ".eslintrc.json"
  - ".stylelintrc.json"
  - ".prettierrc.json"
  - ".prettierignore"

keep_files:
  - assets/dist
